name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.21
  - geopandas=0.14.2
  - jupyter=1.1.1
  - matplotlib=3.9.2
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - scipy=1.12.0
  - seaborn=0.13.2
  - shapely=2.0.6
  - pip
  - pip:
      - hdf5plugin==5.0.0
      - alphashape==1.3.1
      - anndata==0.10.9
      - editdistance==0.8.1
      - google==3.0.0
      - google-cloud-storage==2.19.0
      - gseapy==1.1.4
      - libpysal==4.8.1
      - lowess==1.0.3
      - matplotlib-scalebar==0.9.0
      - matplotlib-venn==1.1.1
      - multiprocess==0.70.17
      - openpyxl==3.1.5
      - pickle5==0.0.11
      - scanpy==1.10.3
      - scikit-bio==0.6.3
      - squidpy==1.6.1
